services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laundry_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - laundry_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laundry_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - laundry_network

networks:
  laundry_network:
    name: laundry_network
